### PR TITLE
Wrap all potential JedisConnectionError with RepsheetCoonectionException

### PR DESCRIPTION
**Pull request by roboxue**
When using librepsheet, importing JedisConnectionException looks awkward. (My personal feeling). So I wrapped up every potential connection exception with Repsheet exception. What do you think?

### CODE REVIEW

**Comment by abedra** [comment]
Did you run the tests after this? I imagine it would have an impact. The CI process is broken and I need to get it fixed (maven nonsense to skip the gpg signing part during the build on ci)

**Comment by roboxue** [comment]
I have eight dump tests that I didn't submit in this PR, let me push that through :)

**Comment by abedra** [comment]
I just want to make sure the test suite still passes after this, that's all.

**Comment by roboxue** [comment]
Yes they did. I used Intellij's test function, not calling mvn test however

**Comment by roboxue** [comment]
Submitted my unit tests in this PR. Do you think they are necessary?

**Comment by abedra** [comment]
Let's keep them. I am heading to the airport shortly, but will cut 0.0.3 while I am on the plane.

**Comment by abedra** [comment]
Also, Thanks!

**Pull request merged**
